### ISSUE TITLE
Problems after viewing several skins with pages at 50/100 with the extension

### ISSUE THREAD

**Issue by w1g1** [csgofloat/extension#125]
Greetings good afternoon, since last week I and several friends have seen that steam when viewing various skins with its page maximum 100 items per page, sends an error saying that too many requests have been made, this previously did not happen (no I have no other extension other than the csgofloat extension since it seems to me the most complete and simple to use) I don't know if steam will be implementing something or if the update of the extension is giving an error, so check and verify if something it is happening it should be noted that free cache, etc. of the chrome browser and it still persists once you can see skins after 15 min the error returns, grateful

bug image:

https://postimg.cc/N5L85H5p

**Comment by Step7750** [comment]
Have you tried uninstalling the extension and seeing if that fixes your issue?

I suspect this is all related to Steam changing rate limits.

**Comment by w1g1** [comment]
Greetings, I uninstalled yesterday and today the market was fine without problems, I installed the extension and I saw several skins with 100 sample iems and it threw the error again.

**Comment by Step7750** [comment]
If you use a page size of 10 instead of 100, do you still encounter issues with the extension installed?

**Comment by w1g1** [comment]
I will wait for it to return to normal, install the extension again and try

**Comment by Step7750** [comment]
@w1g1 Any updates?

**Comment by Step7750** [comment]
@w1g1 Ping, otherwise I'll close this issue.

**Comment by w1g1** [comment]
Greetings, I was busy, in fact I stopped using the extension and there was no blockage, as soon as I installed it and I saw some skins with more than 4 pages in items 100, the error came back, I really don't know what it is anymore.

**Comment by Step7750** [comment]
@w1g1 If you use a page size of 10 instead of 100, do you still encounter issues with the extension installed?

**Comment by Step7750** [comment]
This is likely related to Steam rate limits and not the extension, closing.
