### ISSUE TITLE
Colors of floats with problems / Extension

### ISSUE THREAD

**Issue by w1g1** [csgofloat/extension#131]
Regards, I don't know if they have been told, it reports this error that comes from the last update when a color is placed, for example, for
 
float < 0.009
and another for
float < 0.000999999999

or float >= 0.999 and float < 0.9999999999999

both colors are mixed, not giving the pantone tonality that one places apart that the letters of the Float / Paint Seed become so clear that it cannot be seen depending on the light color that they are placed,

I am writing this here because I know that you are always attentive to improve the extension, ty

**Comment by Step7750** [comment]
This is related to automatically changing the text contrast based on background color.

Fixed in #124
