### ISSUE TITLE
CSGOFloat TypeError: Failed to fetch

### ISSUE THREAD

**Issue by HoKiG** [csgofloat/extension#133]
Hello, I'm having trouble with viewing floats for skins whenever I use the community market. No matter the sample size it says "CSGOFloat TypeError: Failed to fetch" or "CSGOFloat Error: Queue size is full, please try again later". If anyone has a solution I would appreciate it.

**Comment by HoKiG** [comment]
I also tried reinstalling the extensions but the results were the same

**Comment by HoKiG** [comment]
It might be because of Valve. After I posted this I saw a tweet from the CSGOFloat official twitter page saying Valve limited requests.
![tweet](https://user-images.githubusercontent.com/131523033/234101950-9ba41dc9-ac41-48e0-b094-0e6005c0bdbe.PNG)

**Comment by Step7750** [comment]
This is more reliable now, closing.
