### ISSUE TITLE
SIH Breaks Float Extension

### ISSUE THREAD

**Issue by bury2** [csgofloat/extension#139]
might be a me thing but might not 

SIH+csgofloat market extensions display the same stickers twice, hides names and float values, sort by float stops working, and next page button is intermittent.

![image](https://github.com/csgofloat/inspect/assets/130941166/30da5780-4503-457e-84c2-911c9c4750b8)

**Comment by Step7750** [comment]
Sorry, but extension compatibility is difficult to achieve on both ends here. For the time being, we aren't planning to mutate how CSGOFloat works in order to accommodate SIH.
