### ISSUE TITLE
Error CSGOFloat TypeError: Failed to fetch on Chrome

### ISSUE THREAD

**Issue by jjjimm** [csgofloat/extension#149]
After checking a certain number of pages on the Steam trading platform, an error occurs CSGOFloat TypeError: Failed to fetch. VPN does not help, reinstalling the extension does not help, there are no conflicting extensions. Previously, I could easily browse a large number of pages, but now after 10-20 pages, this error appears. I apologize for my poor language skills, I am ready to provide the necessary information if needed. 
![image](https://github.com/csgofloat/extension/assets/136233161/9435e699-eb82-47a6-9f89-4698fd9f9e70)
![image](https://github.com/csgofloat/extension/assets/136233161/4dcfb05c-9110-4756-bc84-41d906a78366)
The error occurs not on every item, but out of 100 items, around 50 of them may be erroneous.

**Comment by Lunderfuglen** [comment]
any updates on this? Im getting the same bug on all items :/

**Comment by Step7750** [comment]
If you're using a VPN, turn it off. 

We also have many IP blocks that are banned due to abuse -- it's possible you're under one of them.
