### ISSUE TITLE
Improve Market Hash Fragment

### ISSUE THREAD

**Issue by Soniclev** [csgofloat/extension#89]
Some apps like Telegram encodes URL, that is why hash part of url will be like `#buylisting%7C3126012155444962045%7C730%7C2%7C19106738906` but not like `#buylisting|3126012155444962045|730|2|19106738906`. Function `MarketCheckHash` accepts only `|` symbol, but not `%7C`. 
```js
if ( window.location.hash.length > 4 && window.location.hash.substr(0,4) == "#buy" )
{
	var rgListing = window.location.hash.substr(4).split('|');
	BuyMarketListing( rgListing[0], rgListing[1], rgListing[2], rgListing[3], rgListing[4] );
}
```
It will be great, if this extension will fixing hash part of URL before function `MarketCheckHash` was called.

**Comment by Step7750** [comment]
Thanks for the suggestion, but I'd prefer that we don't mutate some core functions on the page for now.
