### ISSUE TITLE
'QuotaExceededError'

### ISSUE THREAD

**Issue by iDEaXANA** [csgofloat/extension#91]
Happens everytime i want to delete a filter or add one. I've had about 100 or so filters for a while now but only today is it bringing me this error when i wanted to add 3 more.

Error occurred while saving, you may have to remove some filters and try again
Error: QuotaExceededError: storage.sync API call exceeded its quota limitations

Thanks.

**Comment by iDEaXANA** [comment]
Can anyone help...?

I tried removing the add-on hoping the customisations would be removed but they're saved somewhere. no idea where though.

**Comment by Step7750** [comment]
This should generally be resolved with the extension rewrite in 2022.
