### ISSUE TITLE
High CPU usage on inventory page if used with Steam Inventory Helper

### ISSUE THREAD

**Issue by zyoi** [csgofloat/extension#92]
It looks like either of the extensions is being stuck in an infinite loop which causes high CPU usage. 

This was a much more problematic behavior for me when I used 4threads/4cores instead of 8threads/4cores on my CPU and a few opened tabs could use most of my CPU.

On screenshot I've opened 4 tabs with inventories.

![image](https://user-images.githubusercontent.com/13048272/90519195-637dd880-e170-11ea-8633-ca54f8967c98.png)

**Comment by Step7750** [comment]
Does this issue still occur with only SIH installed?

**Comment by zyoi** [comment]
No, it doesn't. 

Screenshot with only SIH enabled:
![image](https://user-images.githubusercontent.com/13048272/90532630-23beed00-e180-11ea-9e0a-393eb74cde81.png)

**Comment by Step7750** [comment]
This issue is likely no longer relevant with the rewrite in 2022.
